services:

  pocketbase:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        PB_VERSION: "0.36.7"
    ports:
      - "8099:8090"
    volumes:
      - pb_data:/pb/pb_data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8090/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PB_URL: "https://daniel.api.techdani.cc"
    ports:
      - "809:80"
    depends_on:
      pocketbase:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pb_data:
